version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your-database-name
      - DB_USERNAME=your-database-username
      - DB_PASSWORD=your-database-password
      - API_KEY=Bs)ovNuDm*p0nevjZMz53RjXfX7)_Q
      - BASE_API_URL=https://qa.alephmanager.com/
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your-database-name
      MYSQL_USER: your-database-username
      MYSQL_PASSWORD: your-database-password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql-data:
