services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=80
    envVars:
      - key: APP_KEY
        value: ${APP_KEY}  # La clave de tu aplicación
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-render-url.com  # Cambiar por la URL de tu aplicación
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host.render.com  # La URL de tu base de datos si usas Render DB
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-username
      - key: DB_PASSWORD
        value: your-database-password
      - key: API_KEY
        value: Bs)ovNuDm*p0nevjZMz53RjXfX7)_Q
      - key: BASE_API_URL
        value: https://qa.alephmanager.com/
    plan: free
